version: '3'

services:

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  php:
    image: php:7.3-fpm
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}

  mariadb:
    image: mariadb:10.3
    restart: always
    volumes:
      - ${DB_PATH_HOST}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwerty

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb:db
    ports:
      - 8765:80
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
    depends_on:
      - mariadb

  composer:
    image: composer:1.8
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}
    command: composer install